image: node:latest

pipelines:
  default:
    - step:
        name: Build and test
        image: gradle:5.6-jdk11
        caches:
          - gradle
        script:
          - bash ./gradlew clean build
    - step:
        name: Deploy Backend to production
        deployment: production
        script:
          - apt-get update -qy
          - apt-get install -y ruby-dev
          - gem install dpl
          - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    - step:
        name: Deploy frontend to production
        deployment: production
        script:
          - cd frontend
          - apt-get update -qy
          - apt-get install -y ruby-dev
          - gem install dpl
          - dpl --provider=heroku --app=$HEROKU_FRONTEND_APP_NAME --api-key=$HEROKU_API_KEY