image: node:latest

pipelines:
  default:
    - step:
        name: Build and test
        image: gradle:5.6-jdk11
        caches: 
          - gradle
        script:
          - bash ./gradlew clean build
   