image: node:latest

pipelines:
  default:
    - step:
        name: Build and test
        image: gradle:5.6-jdk11
        caches: 
          - gradle
        script:
          - ./gradlew clean build
    - step:
        name: Deploy to production
        image: node:latest
        deployment: production
        script:
          - apt-get update -qy
          - apt-get install -y ruby-dev
          - gem install dpl
          - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
